# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ozfXRBz84bnZEneTFy2bvnzWHbWEPOhe

Installing dependancies
"""



"""Creating FastAPI"""

from fastapi import FastAPI

app = FastAPI()

@app.get("/")
def read_root():
    return {"message": "Welcome to the Text Classification API"}

"""Loading Pretrained Model from Huggingface"""

from fastapi import FastAPI
from transformers import pipeline

app = FastAPI()

# Load pre-trained sentiment analysis model
classifier = pipeline("sentiment-analysis")

@app.post("/classify_sentiment/")
async def classify_sentiment(text: str):
    result = classifier(text)
    return {"sentiment": result[0]['label'], "confidence": result[0]['score']}



